version: '3.9'
services:
  word_embd_server:
    image: ozxx33/kgqan_word_embedding
    ports:
      - '9600:9600'
    volumes:
      - ./data/wiki-news-300d-1M.txt:/app/data/wiki-news-300d-1M.txt
    networks:
      - kgqan_network
    restart: always

  kgqan_server:
    image: ozxx33/kgqan_server
    ports:
      - '8899:8899'
    volumes:
      - ./data/output_pred21_8_30:/app/model
      - ./src:/app
    environment:
      - WORD_EMBEDDING_HOST=word_embd_server
      - WORD_EMBEDDING_PORT=9600
    depends_on:
      - word_embd_server
    networks:
      - kgqan_network
    restart: always

networks:
  kgqan_network:
